ADD: CAMINO_DIR setting
git-svn-id: https://www.nitrc.org/svn/cmtk/trunk@4641 42a5c34f-2066-0410-bec5-ba365beb4995

diff --git a/core/contrib/ncanda/ncanda_setup.sh.in b/core/contrib/ncanda/ncanda_setup.sh.in
--- a/core/contrib/ncanda/ncanda_setup.sh.in
+++ b/core/contrib/ncanda/ncanda_setup.sh.in
@@ -107,3 +107,21 @@ fsl()
 }
 
 
+
+#
+# Set up Camino
+#
+
+export CAMINO_DIR=${CAMINO_DIR:-@CMTK_CAMINO_DIR@}
+
+if [ "${CAMINO_DIR}" = "" ]; then
+    echo "ERROR: must set 'CAMINO_DIR' environment variable to Camino root directory"
+    exit 1
+fi
+
+camino()
+{
+    ${CAMINO_DIR}/bin/$*
+}
+
+
