ADD: check for matching geometries
git-svn-id: https://www.nitrc.org/svn/cmtk/trunk@5298 42a5c34f-2066-0410-bec5-ba365beb4995

diff --git a/core/scripts/correct_dwi_distortion.in b/core/scripts/correct_dwi_distortion.in
--- a/core/scripts/correct_dwi_distortion.in
+++ b/core/scripts/correct_dwi_distortion.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 ##
-##  Copyright 2012, 2013 SRI International
+##  Copyright 2012-2014 SRI International
 ##
 ##  This file is part of the Computational Morphometry Toolkit.
 ##
@@ -47,6 +47,13 @@ fi
 outdir=$1
 b0Rev=$2
 b0Fwd=$3
+
+if ! cmtk geomatch ${b0Rev} ${b0Fwd}; then
+    echo "ERROR: the two b=0 images have mismatched geometries or spatial coordinated:"
+    echo "  ${b0Rev}"
+    echo "  ${b0Fwd}"
+    exit 1
+fi
 
 shift 3
 bXlist="$*"
