ADD: verbose geometry check
git-svn-id: https://www.nitrc.org/svn/cmtk/trunk@5299 42a5c34f-2066-0410-bec5-ba365beb4995

diff --git a/core/scripts/correct_dwi_distortion.in b/core/scripts/correct_dwi_distortion.in
--- a/core/scripts/correct_dwi_distortion.in
+++ b/core/scripts/correct_dwi_distortion.in
@@ -48,8 +48,8 @@ outdir=$1
 b0Rev=$2
 b0Fwd=$3
 
-if ! cmtk geomatch ${b0Rev} ${b0Fwd}; then
-    echo "ERROR: the two b=0 images have mismatched geometries or spatial coordinated:"
+if ! cmtk geomatch -v ${b0Rev} ${b0Fwd}; then
+    echo "ERROR: the two b=0 images have mismatched geometries or spatial coordinates:"
     echo "  ${b0Rev}"
     echo "  ${b0Fwd}"
     exit 1
